apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sgi-esb-external.fullname" . }}
  labels:
    {{- include "sgi-esb-external.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sgi-esb-external.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.annotations.enabled }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.annotations.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}  
      labels:
        {{- include "sgi-esb-external.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sgi-esb-external.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: postgres-container
          image: postgres:12
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_DB
            value: db
          ports:
            - containerPort: 5432
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ required "An image.repository value must be specified" .Values.image.repository }}:{{ required "An image.tag value must be specified" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # need to streamline this
          env:
          - name: SERVER_PORT
            value: {{ .Values.server.port | quote }}
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.spring.datasourceUrl | quote }}
          - name: SPRING_LIQUIBASE_CONTEXTS
            value: {{ .Values.spring.liquibaseContexts | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.server.port }}
              protocol: TCP
          # commented out until clarified
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
